apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: hiro-plugin-example
  name: guestbook-ui
  namespace: secure-ns
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
      project: hiro-plugin-example
  template:
    metadata:
      labels:
        app: guestbook-ui
        project: hiro-plugin-example
    spec:
      containers:
      - image: IMAGE_PLACEHOLDER
        name: guestbook-ui
        ports:
        - containerPort: 80

