apiVersion: v1
kind: Service
metadata:
  labels:
    project: hiro-plugin-example
  name: guestbook-ui
  namespace: secure-ns
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
    project: hiro-plugin-example
